# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- Maintenance_API_Patch1

pool:
 vmImage: 'ubuntu-latest'

steps:
- script: |
   az login --service-principal -u $(appid) -p $(secret) --tenant $(tenent)
   cd StorageCondition_API
   az acr build --image netsc:v$(Build.BuildId) --registry acrscnonprod --file Dockerfile .
   az extension add --name containerapp --upgrade
   az containerapp update --name containernetscnoprod --resource-group rg-20060000-storageconditions-NonProd --image acrscnonprod.azurecr.io/netsc:v$(Build.BuildId)   
  displayName: 'Build and Deploy'
